name: CI

on:
  push:
    branches:
      - main
      - second

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Nachricht für Main Branch
        if: github.ref == 'refs/heads/main'
        run: echo "Das ist der MAIN Branch!"

      - name: Nachricht für Dev Branch
        if: github.ref == 'refs/heads/dev'
        run: echo "Das ist der DEV Branch!"