name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '10 13 * * *'  # Winter

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Your Code
        uses: actions/checkout@v6

      - name: Say Hello to the Worldddd
        run: echo "Hello, World!"