name: CI

on:
  push:
    branches:
      - main
      - second

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Your Code
        uses: actions/checkout@v2

      - name: Say Hello to Main Branch
        if: github.ref == 'refs/heads/main'
        run: echo "Hello from MAIN Branch!"

      - name: Say Hello to Second Branch
        if: github.ref == 'refs/heads/second'
        run: echo "Hello from SECOND Branch!"